### Create Order
POST http://localhost:19093/order-services/
X-AUTH-TOKEN: asdfghjklzxc
Content-Type: application/json

{
    "symbol": "BOB",
    "quantity": 10
}

### Update Order
PUT http://localhost:19093/order-services/
X-AUTH-TOKEN: asdfghjklzxc
Content-Type: application/json

{
    "identifier": "",
    "quantity": 15
}
### Delete Order
DELETE http://localhost:19093/order-services/
X-AUTH-TOKEN: asdfghjklzxc
Content-Type: application/json

{
    "identifier": "b4f39d9f-d2c5-485c-9b94-44636c018694"
}
### Status
POST http://localhost:19093/order-services/status
X-AUTH-TOKEN: asdfghjklzxc
Content-Type: application/json

{
    "identifier": "b4f39d9f-d2c5-485c-9b94-44636c018694"
}




### PUT
PUT https://prototype.sbulltech.com/api/order/"20a521de-474a-4d0e-935b-896c85ba859c"
X-AUTH-TOKEN: asdfghjklzxc
Content-Type: application/application/json

{
    "quantity": 10
}
### Get update
POST https://prototype.sbulltech.com/api/order/status-for-ids
X-AUTH-TOKEN: asdfghjklzxc
Content-Type: application/json

{
    "order_ids": ["20a521de-474a-4d0e-935b-896c85ba859c"]
}