GET http://localhost:19093/order_services/
###
GET http://localhost:19093/order_services/status/64b7bf606bc3f97dc6439f9c
###
POST http://localhost:19093/order_services
Content-Type: application/json

{
    "symbol": "SBI",
    "quantity": 10
}
###
DELETE http://localhost:19093/order_services/64b7bc654ad34d2699589906
###
PATCH http://localhost:19093/order_services/64b7bf606bc3f97dc6439f9c
Content-Type: application/json

{
    "identifier": "ORDER-1689763680605",
    "new_quantity": 20
}